var manifest = [
    {
        src:"lib/assets.json",
        forSpritesheet:"assets"
    },
    {
        src:"lib/assets.png",
        id:"assets"
    }, 
    {
        src:"lib/startmusic.wav",
        id:"startMusic",
        data:4
    },
    {
        src:"lib/levelup.wav",
        id:"Levelup",
        data:4
    },
    {
        src:"lib/gamemusic.wav",
        id:"gameMusic",
        data:4
    },
     {
        src:"lib/gamemusic2.wav",
        id:"gameMusic2",
        data:4
    },
     {
        src:"lib/gamemusic3.wav",
        id:"gameMusic3",
        data:4
    },
    {
        src:"lib/launch.wav",
        id:"launch",
        data:4
    },
    {
        src:"lib/bounce.wav",
        id:"bounce",
        data:4
    },
    {
        src:"lib/brickhit.wav",
        id:"brickhit",
        data:4
    },
    {
        src:"lib/death.wav",
        id:"death",
        data:4
    },
    {
        src:"lib/gamewin.wav",
        id:"gamewin",
        data:4
    }
];